### ISSUE TITLE
Document setting Environments for chef provisioner

### ISSUE THREAD

**Issue by cheeseplus** [test-kitchen/kitchen-docs#73]
```
provisioner:
  name: chef_zero
  environments_path: test/environments
  client_rb:
    environment: kitchen
```

For posterity we should note `solo_rb` vs `client_rb` even though nobody should need it at this juncture. Also note files in `environments_path` must be JSON
